name: Post JSON File to Two URLs

on:
  push:
    branches:
      - main # Runs only when pushing to the main branch
  workflow_dispatch: # Allows manual trigger
  
jobs:
  post_json:
    runs-on: ubuntu-latest
    steps:
        - name: Checkout Repository
          uses: actions/checkout@v3

        - name: Send JSON Data to First URL
          run: |
            curl -X POST "https://:K8QPD882QUqS2H2cHqJpPQ@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:x5c0Ci3BS22rpTtS_MceMg/streams/AQAAAPagxrKVpEwngahDnGj_ABsAAAAA" \
                -H "Content-Type: application/json" \
                -d @stream.json
                
        - name: Send JSON Data to Second URL
          run: |
            curl -X POST "https://:WbshxJHCTQeSRSA2C6Nt6w@tandem.autodesk.com/api/v1/timeseries/models/urn:adsk.dtm:x5c0Ci3BS22rpTtS_MceMg/streams/AQAAAPdz5lHsUExUtBRHrf2rm4AAAAAA" \
                -H "Content-Type: application/json" \
                -d @stream.json
